### ISSUE TITLE
stylesheet has wrong mime type

### ISSUE THREAD

**Issue by btrem** [paulhtremblay/covid19#27]
The stylesheet /styles/site.css is being served with a mime type text/html, which is wrong, and causing it to not be loaded. The correct mime type is text/css. Also, the make.sh script creates site.css in the wrong place. It makes it in /styles/styles/site.css, instead of /styles/site.css

**Comment by paulhtremblay** [comment]
fixed

**Comment by btrem** [comment]
make.sh still creates /styles/styles/site.css instead of /styles/site.css

**Comment by btrem** [comment]
Ok, this git thing is really confusing. I just made a change to make.sh and pushed my change, but it merged it with master. Sorry about that. You should review the change I made (just one line in make.sh to make sure it's ok, because it's now in master.

**Comment by paulhtremblay** [comment]
What branch were you on?

**Comment by paulhtremblay** [comment]
![image](https://user-images.githubusercontent.com/1154297/82846078-f70a7a80-9e9b-11ea-9702-85b6f8b4d20d.png)

**Comment by paulhtremblay** [comment]
It is putting it in the right place. Where are you seeing it in the wrong place?

**Comment by btrem** [comment]
When I run bash make.sh, it copies /templates/styles/site.css to /html_temp/styles/styles/site.css

NB: I just pushed a change to master to correct this cf. https://github.com/paulhtremblay/covid19/issues/27#issuecomment-633730758

**Comment by paulhtremblay** [comment]
I fixed this in master as well. do
git pull

But you should be developing in a branch off master
git checkout -b <what I want to do>
git commit -am "what i did"
git push
<code review for merge into master>

**Comment by btrem** [comment]
> you should be developing in a branch off master

Yeah, I know. See
https://github.com/paulhtremblay/covid19/issues/27#issuecomment-633730758

**Comment by paulhtremblay** [comment]
Change should not have merged automatically. Not sure why that happened.

**Comment by btrem** [comment]
I notice you added a type attribute to the `<link>` element in base.j2 `<head>` linking the stylesheet. This does not resolve the mime type issue. Amazon s3 server is not sending a mime type in the response headers as it should. More info here:

https://stackoverflow.com/questions/2618168/amazon-s3-is-not-serving-files-correctly

Note that the type attribute in the `<link>` element is unnecessary. (The http header is authoritative.)
